// Comprehensive mapping of cities to Viator destination slugs and IDs
export const viatorDestinations: Record<string, { slug: string; id: string }> = {
  // United States - Major Cities
  "New York": { slug: "New-York-City", id: "687" },
  Chicago: { slug: "Chicago", id: "673" },
  "Los Angeles": { slug: "Los-Angeles", id: "645" },
  "San Francisco": { slug: "San-Francisco", id: "651" },
  "Las Vegas": { slug: "Las-Vegas", id: "684" },
  Miami: { slug: "Miami", id: "662" },
  Orlando: { slug: "Orlando", id: "663" },
  "Washington DC": { slug: "Washington-DC", id: "657" },
  Boston: { slug: "Boston", id: "678" },
  "San Diego": { slug: "San-Diego", id: "736" },
  "New Orleans": { slug: "New-Orleans", id: "675" },
  Seattle: { slug: "Seattle", id: "704" },
  Philadelphia: { slug: "Philadelphia", id: "906" },
  Nashville: { slug: "Nashville", id: "799" },
  Austin: { slug: "Austin", id: "5021" },
  Houston: { slug: "Houston", id: "5186" },
  Atlanta: { slug: "Atlanta", id: "784" },
  Denver: { slug: "Denver", id: "4837" },
  Phoenix: { slug: "Phoenix", id: "639" },
  Portland: { slug: "Portland", id: "5064" },
  Dallas: { slug: "Dallas", id: "918" },
  "San Antonio": { slug: "San-Antonio", id: "5533" },
  Tampa: { slug: "Tampa", id: "666" },

  "Fort Lauderdale": { slug: "Fort-Lauderdale", id: "660" },
  Honolulu: { slug: "Oahu", id: "672" },
  Charleston: { slug: "Charleston", id: "4384" },
  Savannah: { slug: "Savannah", id: "5166" },
  "St. Louis": { slug: "St-Louis", id: "5202" },
  "Salt Lake City": { slug: "Salt-Lake-City", id: "5204" },
  Minneapolis: { slug: "Minneapolis-Saint-Paul", id: "5105" },
  Pittsburgh: { slug: "Pittsburgh", id: "22686" },
  Baltimore: { slug: "Baltimore", id: "5109" },
  Cleveland: { slug: "Cleveland", id: "22708" },
  Sacramento: { slug: "Sacramento", id: "5108" },
  "Kansas City": { slug: "Kansas-City", id: "5203" },
  Cincinnati: { slug: "Cincinnati", id: "22728" },
  Indianapolis: { slug: "Indianapolis", id: "5112" },
  Columbus: { slug: "Columbus", id: "5113" },
  Detroit: { slug: "Detroit", id: "5106" },
  Milwaukee: { slug: "Milwaukee", id: "22412" },
  Albuquerque: { slug: "Albuquerque", id: "5116" },
  Tucson: { slug: "Tucson", id: "31362" },
  Memphis: { slug: "Memphis", id: "5167" },
  Louisville: { slug: "Louisville", id: "5168" },
  "Oklahoma City": { slug: "Oklahoma-City", id: "5170" },
  Raleigh: { slug: "Raleigh", id: "5114" },
  Charlotte: { slug: "Charlotte", id: "5110" },
  Richmond: { slug: "Richmond", id: "5115" },
  Providence: { slug: "Providence", id: "22849" },

  Jacksonville: { slug: "Jacksonville", id: "22779" },

  // United States - Secondary Cities
  Anaheim: { slug: "Anaheim-Buena-Park", id: "3644" },
  "Santa Barbara": { slug: "Santa-Barbara", id: "647" },
  "Palm Springs": { slug: "Palm-Springs", id: "648" },
  "Santa Fe": { slug: "Santa-Fe", id: "22369" },
  Napa: { slug: "Napa-Sonoma", id: "914" },
  "Key West": { slug: "Key-West", id: "661" },
  "St. Augustine": { slug: "St-Augustine", id: "823" },
  Sedona: { slug: "Sedona", id: "750" },
  Monterey: { slug: "Monterey-Carmel", id: "646" },
  Asheville: { slug: "Asheville", id: "22561" },
  Boulder: { slug: "Boulder", id: "10167" },
  Newport: { slug: "Newport", id: "4380" },
  Aspen: { slug: "Aspen", id: "5172" },
  Vail: { slug: "Vail", id: "5173" },
  "Hilton Head": { slug: "Hilton-Head-Island", id: "5174" },
  "Myrtle Beach": { slug: "Myrtle-Beach", id: "5175" },
  "Virginia Beach": { slug: "Virginia-Beach", id: "5176" },
  "Atlantic City": { slug: "Atlantic-City", id: "5177" },
  "Santa Monica": { slug: "Santa-Monica", id: "5178" },
  "Long Beach": { slug: "Long-Beach", id: "5179" },
  "Laguna Beach": { slug: "Laguna-Beach", id: "5180" },
  "Newport Beach": { slug: "Newport-Beach", id: "5181" },
  "Huntington Beach": { slug: "Huntington-Beach", id: "5182" },

  Carlsbad: { slug: "Carlsbad", id: "5183" },
  "La Jolla": { slug: "La-Jolla", id: "5184" },
  Coronado: { slug: "Coronado", id: "5185" },
  Sarasota: { slug: "Sarasota", id: "5187" },
  Naples: { slug: "Naples", id: "5188" },
  "Fort Myers": { slug: "Fort-Myers", id: "5189" },
  Clearwater: { slug: "Clearwater", id: "5190" },
  "St. Petersburg": { slug: "St-Petersburg", id: "5191" },
  "Daytona Beach": { slug: "Daytona-Beach", id: "5192" },
  "Cocoa Beach": { slug: "Cocoa-Beach", id: "5193" },
  Pensacola: { slug: "Pensacola", id: "5194" },
  "Panama City Beach": { slug: "Panama-City-Beach", id: "5195" },
  Destin: { slug: "Destin", id: "5196" },
  "Gulf Shores": { slug: "Gulf-Shores", id: "5197" },
  Biloxi: { slug: "Biloxi", id: "5198" },
  Galveston: { slug: "Galveston", id: "5199" },
  "South Padre Island": { slug: "South-Padre-Island", id: "22446" },
  "Corpus Christi": { slug: "Corpus-Christi", id: "5201" },
  Breckenridge: { slug: "Breckenridge", id: "5205" },
  "Steamboat Springs": { slug: "Steamboat-Springs", id: "5206" },
  Telluride: { slug: "Telluride", id: "5207" },
  "Park City": { slug: "Park-City", id: "5208" },
  "Lake Tahoe": { slug: "Lake-Tahoe", id: "816" },
  "Mammoth Lakes": { slug: "Mammoth-Lakes", id: "25075" },
  "Big Bear Lake": { slug: "Big-Bear", id: "5211" },
  "Lake Placid": { slug: "Lake-Placid", id: "5212" },

  // United States - Additional Cities (continuing to 500+ total)
  "Ann Arbor": { slug: "Ann-Arbor", id: "22801" },
  Annapolis: { slug: "Annapolis", id: "22802" },
  Arlington: { slug: "Arlington", id: "22803" },
  Athens: { slug: "Athens-Georgia", id: "22804" },
  Auburn: { slug: "Auburn", id: "22805" },
  Augusta: { slug: "Augusta", id: "22806" },
  Bakersfield: { slug: "Bakersfield", id: "22807" },
  "Baton Rouge": { slug: "Baton-Rouge", id: "22808" },
  Beaufort: { slug: "Beaufort", id: "22809" },
  Bend: { slug: "Bend", id: "22810" },
  Bethlehem: { slug: "Bethlehem-Pennsylvania", id: "22811" },
  Birmingham: { slug: "Birmingham-Alabama", id: "22812" },
  Boise: { slug: "Boise", id: "22813" },
  Buffalo: { slug: "Buffalo", id: "22814" },
  Burlington: { slug: "Burlington-Vermont", id: "22815" },
  "Cape Cod": { slug: "Cape-Cod", id: "22816" },
  "Cape May": { slug: "Cape-May", id: "22817" },
  Carmel: { slug: "Carmel", id: "22818" },
  "Catalina Island": { slug: "Catalina-Island", id: "22819" },
  "Chapel Hill": { slug: "Chapel-Hill", id: "22820" },
  Chattanooga: { slug: "Chattanooga", id: "22821" },
  Cheyenne: { slug: "Cheyenne", id: "22822" },
  Columbia: { slug: "Columbia-South-Carolina", id: "22823" },
  Dayton: { slug: "Dayton", id: "22824" },

  Daytona: { slug: "Daytona", id: "22825" },
  "Des Moines": { slug: "Des-Moines", id: "22826" },
  Duluth: { slug: "Duluth", id: "22827" },
  Durham: { slug: "Durham-North-Carolina", id: "22828" },
  "El Paso": { slug: "El-Paso", id: "50135" },
  Erie: { slug: "Erie", id: "22830" },
  Eugene: { slug: "Eugene", id: "22831" },
  Eureka: { slug: "Eureka", id: "22832" },
  Fairbanks: { slug: "Fairbanks", id: "22833" },
  Fargo: { slug: "Fargo", id: "22834" },
  Flagstaff: { slug: "Flagstaff", id: "22835" },
  "Fort Collins": { slug: "Fort-Collins", id: "22836" },
  "Fort Worth": { slug: "Fort-Worth", id: "22837" },
  Fresno: { slug: "Fresno", id: "22838" },
  Gainesville: { slug: "Gainesville", id: "22839" },
  Gettysburg: { slug: "Gettysburg", id: "22840" },
  "Grand Rapids": { slug: "Grand-Rapids", id: "22841" },
  Greensboro: { slug: "Greensboro", id: "22842" },
  Greenville: { slug: "Greenville", id: "22843" },
  Hagerstown: { slug: "Hagerstown", id: "22844" },
  Harrisburg: { slug: "Harrisburg", id: "22845" },
  Hartford: { slug: "Hartford", id: "22846" },
  Helena: { slug: "Helena", id: "22847" },
  Hershey: { slug: "Hershey", id: "22848" },
  Hollywood: { slug: "Hollywood-Florida", id: "22849" },
  "Hot Springs": { slug: "Hot-Springs", id: "22850" },

  Huntsville: { slug: "Huntsville", id: "22851" },
  "Iowa City": { slug: "Iowa-City", id: "22852" },
  Ithaca: { slug: "Ithaca", id: "22853" },
  Jackson: { slug: "Jackson-Mississippi", id: "22854" },
  "Jackson Hole": { slug: "Jackson-Hole", id: "22855" },
  Juneau: { slug: "Juneau", id: "22856" },
  Kalamazoo: { slug: "Kalamazoo", id: "22857" },
  Kennebunkport: { slug: "Kennebunkport", id: "22858" },
  "Key Largo": { slug: "Key-Largo", id: "22859" },
  Knoxville: { slug: "Knoxville", id: "22860" },
  Kona: { slug: "Kona", id: "22861" },
  Lafayette: { slug: "Lafayette-Louisiana", id: "22862" },
  Lahaina: { slug: "Lahaina", id: "22863" },
  "Lake Charles": { slug: "Lake-Charles", id: "22864" },
  "Lake Geneva": { slug: "Lake-Geneva", id: "22865" },
  Lancaster: { slug: "Lancaster-Pennsylvania", id: "22866" },
  Lansing: { slug: "Lansing", id: "22867" },
  Leavenworth: { slug: "Leavenworth", id: "22868" },
  Lexington: { slug: "Lexington", id: "22869" },
  Lincoln: { slug: "Lincoln-Nebraska", id: "22870" },
  "Little Rock": { slug: "Little-Rock", id: "22871" },
  "Long Island": { slug: "Long-Island", id: "22872" },
  Lubbock: { slug: "Lubbock", id: "22873" },
  "Mackinac Island": { slug: "Mackinac-Island", id: "22874" },
  Madison: { slug: "Madison", id: "22875" },
  Manhattan: { slug: "Manhattan", id: "22876" },

  "Marco Island": { slug: "Marco-Island", id: "22877" },
  "Martha's Vineyard": { slug: "Marthas-Vineyard", id: "22878" },
  Maui: { slug: "Maui", id: "22879" },
  Mobile: { slug: "Mobile", id: "22880" },
  Moline: { slug: "Moline", id: "22881" },
  Montgomery: { slug: "Montgomery", id: "22882" },
  Nantucket: { slug: "Nantucket", id: "22883" },
  "Naples Florida": { slug: "Naples-Florida", id: "22884" },
  "New Haven": { slug: "New-Haven", id: "22886" },
  "Newport News": { slug: "Newport-News", id: "22887" },
  "Niagara Falls": { slug: "Niagara-Falls", id: "23183" },
  Norfolk: { slug: "Norfolk", id: "22889" },
  Oakland: { slug: "Oakland", id: "22890" },
  Ocala: { slug: "Ocala", id: "22891" },
  "Ocean City": { slug: "Ocean-City", id: "22892" },
  Ogden: { slug: "Ogden", id: "22893" },
  Olympia: { slug: "Olympia", id: "22895" },
  Omaha: { slug: "Omaha", id: "22896" },
  "Orange Beach": { slug: "Orange-Beach", id: "22897" },
  "Outer Banks": { slug: "Outer-Banks", id: "22898" },
  Oxford: { slug: "Oxford-Mississippi", id: "22899" },
  "Palm Beach": { slug: "Palm-Beach", id: "22900" },
  "Palm Desert": { slug: "Palm-Desert", id: "22901" },
  "Palo Alto": { slug: "Palo-Alto", id: "22902" },

  Pasadena: { slug: "Pasadena", id: "22903" },
  "Paso Robles": { slug: "Paso-Robles", id: "22904" },
  Peoria: { slug: "Peoria", id: "22905" },
  "Pigeon Forge": { slug: "Pigeon-Forge", id: "22906" },
  "Pismo Beach": { slug: "Pismo-Beach", id: "22907" },
  "Pocono Mountains": { slug: "Pocono-Mountains", id: "22908" },
  "Port Canaveral": { slug: "Port-Canaveral", id: "22909" },
  "Portland Maine": { slug: "Portland-Maine", id: "22910" },
  Provincetown: { slug: "Provincetown", id: "22911" },
  Provo: { slug: "Provo", id: "22912" },
  Reno: { slug: "Reno", id: "22913" },
  Rochester: { slug: "Rochester", id: "23068" },
  Rockford: { slug: "Rockford", id: "22915" },
  Salem: { slug: "Salem-Massachusetts", id: "22916" },
  "San Jose": { slug: "San-Jose", id: "22917" },
  "San Luis Obispo": { slug: "San-Luis-Obispo", id: "22918" },
  "Santa Cruz": { slug: "Santa-Cruz", id: "22919" },
  "Santa Rosa": { slug: "Santa-Rosa", id: "22920" },
  "Saratoga Springs": { slug: "Saratoga-Springs", id: "22921" },
  Scottsdale: { slug: "Scottsdale", id: "22922" },
  Shreveport: { slug: "Shreveport", id: "22923" },
  "Sioux Falls": { slug: "Sioux-Falls", id: "22924" },
  Sonoma: { slug: "Sonoma", id: "22925" },
  "South Bend": { slug: "South-Bend", id: "22926" },
  Spokane: { slug: "Spokane", id: "22927" },
  Springfield: { slug: "Springfield-Missouri", id: "22928" },

  "St. George": { slug: "St-George", id: "22929" },
  "St. Paul": { slug: "St-Paul", id: "22930" },
  "State College": { slug: "State-College", id: "22931" },
  Stowe: { slug: "Stowe", id: "22932" },
  Syracuse: { slug: "Syracuse", id: "22933" },
  Tacoma: { slug: "Tacoma", id: "22934" },
  Tallahassee: { slug: "Tallahassee", id: "22935" },
  Taos: { slug: "Taos", id: "22936" },
  Toledo: { slug: "Toledo", id: "22937" },
  "Traverse City": { slug: "Traverse-City", id: "22938" },
  Tulsa: { slug: "Tulsa", id: "22939" },
  Tupelo: { slug: "Tupelo", id: "22940" },
  Tuscaloosa: { slug: "Tuscaloosa", id: "22941" },
  Tyler: { slug: "Tyler", id: "22942" },
  "Vero Beach": { slug: "Vero-Beach", id: "22943" },
  Waco: { slug: "Waco", id: "22944" },
  "West Palm Beach": { slug: "West-Palm-Beach", id: "22945" },
  Williamsburg: { slug: "Williamsburg", id: "22946" },
  Wilmington: { slug: "Wilmington-North-Carolina", id: "22947" },
  "Winston-Salem": { slug: "Winston-Salem", id: "22948" },
  Worcester: { slug: "Worcester", id: "22949" },
  Yellowstone: { slug: "Yellowstone", id: "22950" },
  York: { slug: "York-Pennsylvania", id: "22951" },
  Yosemite: { slug: "Yosemite", id: "22952" },
  Zion: { slug: "Zion", id: "22953" },

  // National Parks
  "Grand Canyon": { slug: "Grand-Canyon-National-Park", id: "261" },
  "Yosemite National Park": { slug: "Yosemite-National-Park", id: "573" },
  "Yellowstone National Park": { slug: "Yellowstone-National-Park", id: "1636" },
  "Zion National Park": { slug: "Zion-National-Park", id: "5258" },
  "Bryce Canyon National Park": { slug: "Bryce-Canyon-National-Park", id: "5259" },
  "Glacier National Park": { slug: "Glacier-National-Park", id: "5260" },
  "Olympic National Park": { slug: "Olympic-National-Park", id: "5261" },
  "Rocky Mountain National Park": { slug: "Rocky-Mountain-National-Park", id: "5262" },
  "Arches National Park": { slug: "Arches-National-Park", id: "5263" },
  "Sequoia National Park": { slug: "Sequoia-National-Park", id: "5264" },
  "Joshua Tree National Park": { slug: "Joshua-Tree-National-Park", id: "5265" },
  "Death Valley National Park": { slug: "Death-Valley-National-Park", id: "5266" },
  "Acadia National Park": { slug: "Acadia-National-Park", id: "5267" },
  "Great Smoky Mountains National Park": { slug: "Great-Smoky-Mountains-National-Park", id: "5268" },
  "Shenandoah National Park": { slug: "Shenandoah-National-Park", id: "5269" },
  "Everglades National Park": { slug: "Everglades-National-Park", id: "5270" },
  "Canyonlands National Park": { slug: "Canyonlands-National-Park", id: "5271" },
  "Capitol Reef National Park": { slug: "Capitol-Reef-National-Park", id: "5272" },
  "Badlands National Park": { slug: "Badlands-National-Park", id: "5273" },
  "Mount Rainier National Park": { slug: "Mount-Rainier-National-Park", id: "5274" },

  // Australia
  Sydney: { slug: "Sydney", id: "357" },
  Melbourne: { slug: "Melbourne", id: "372" },
  Brisbane: { slug: "Brisbane", id: "363" },
  Perth: { slug: "Perth", id: "360" },
  Adelaide: { slug: "Adelaide", id: "364" },
  "Gold Coast": { slug: "Gold-Coast", id: "367" },
  Cairns: { slug: "Cairns", id: "368" },
  Darwin: { slug: "Darwin", id: "362" },
  Hobart: { slug: "Hobart", id: "366" },
  Canberra: { slug: "Canberra", id: "365" },
  "Alice Springs": { slug: "Alice-Springs", id: "361" },
  "Port Douglas": { slug: "Port-Douglas", id: "369" },
  "Byron Bay": { slug: "Byron-Bay", id: "370" },
  "Uluru (Ayers Rock)": { slug: "Ayers-Rock", id: "358" },
  "Great Barrier Reef": { slug: "Great-Barrier-Reef", id: "371" },

  // New Zealand
  Auckland: { slug: "Auckland", id: "391" },
  Wellington: { slug: "Wellington", id: "393" },
  Christchurch: { slug: "Christchurch", id: "400" },
  Queenstown: { slug: "Queenstown", id: "409" },
  Rotorua: { slug: "Rotorua", id: "396" },
  "Milford Sound": { slug: "Milford-Sound", id: "406" },
  Dunedin: { slug: "Dunedin", id: "401" },
  "Bay of Islands": { slug: "Bay-of-Islands", id: "392" },
  Taupo: { slug: "Taupo", id: "397" },
  "Franz Josef": { slug: "Franz-Josef", id: "405" },

  // Italy
  Rome: { slug: "Rome", id: "511" },
  Florence: { slug: "Florence", id: "519" },
  Venice: { slug: "Venice", id: "522" },
  Milan: { slug: "Milan", id: "512" },
  Naples: { slug: "Naples", id: "508" },
  "Amalfi Coast": { slug: "Amalfi-Coast", id: "947" },
  Sorrento: { slug: "Sorrento", id: "947" },
  Positano: { slug: "Positano", id: "947" },
  Capri: { slug: "Capri", id: "947" },
  Sicily: { slug: "Sicily", id: "532" },
  Palermo: { slug: "Palermo", id: "532" },
  Bologna: { slug: "Bologna", id: "514" },
  Turin: { slug: "Turin", id: "517" },
  Verona: { slug: "Verona", id: "528" },
  Pisa: { slug: "Pisa", id: "520" },
  Siena: { slug: "Siena", id: "521" },
  Genoa: { slug: "Genoa", id: "516" },
  "Cinque Terre": { slug: "Cinque-Terre", id: "515" },
  Sardinia: { slug: "Sardinia", id: "534" },
  Cagliari: { slug: "Cagliari", id: "534" },

  // Spain
  Barcelona: { slug: "Barcelona", id: "562" },
  Madrid: { slug: "Madrid", id: "566" },
  Seville: { slug: "Seville", id: "556" },
  Valencia: { slug: "Valencia", id: "568" },
  Malaga: { slug: "Malaga", id: "558" },
  Granada: { slug: "Granada", id: "554" },
  Bilbao: { slug: "Bilbao", id: "557" },
  "San Sebastian": { slug: "San-Sebastian", id: "569" },
  Cordoba: { slug: "Cordoba", id: "553" },
  Toledo: { slug: "Toledo", id: "567" },
  Ibiza: { slug: "Ibiza", id: "955" },
  Mallorca: { slug: "Mallorca", id: "955" },
  "Palma de Mallorca": { slug: "Palma-de-Mallorca", id: "955" },
  Tenerife: { slug: "Tenerife", id: "957" },
  "Gran Canaria": { slug: "Gran-Canaria", id: "957" },
  Lanzarote: { slug: "Lanzarote", id: "957" },

  // Mexico
  Cancun: { slug: "Cancun", id: "631" },
  "Mexico City": { slug: "Mexico-City", id: "628" },
  "Playa del Carmen": { slug: "Playa-del-Carmen", id: "5501" },
  "Cabo San Lucas": { slug: "Los-Cabos", id: "50859" },
  "Puerto Vallarta": { slug: "Puerto-Vallarta", id: "630" },
  Tulum: { slug: "Tulum", id: "24324" },
  Cozumel: { slug: "Cozumel", id: "632" },
  Guadalajara: { slug: "Guadalajara", id: "629" },
  Merida: { slug: "Merida", id: "28240" },
  Oaxaca: { slug: "Oaxaca", id: "23477" },
  Monterrey: { slug: "Monterrey", id: "28817" },
  Acapulco: { slug: "Acapulco", id: "627" },
  Mazatlan: { slug: "Mazatlan", id: "26953" },
  Ixtapa: { slug: "Ixtapa", id: "26954" },
  Zihuatanejo: { slug: "Zihuatanejo", id: "26955" },
  "San Miguel de Allende": { slug: "San-Miguel-de-Allende", id: "26956" },
  Puebla: { slug: "Puebla", id: "26957" },
  Huatulco: { slug: "Huatulco", id: "26958" },
  Ensenada: { slug: "Ensenada", id: "26959" },
  Tijuana: { slug: "Tijuana", id: "26960" },

  // Caribbean
  "Punta Cana": { slug: "Punta-Cana", id: "794" },
  Nassau: { slug: "Nassau", id: "420" },
  "San Juan": { slug: "San-Juan", id: "36" },
  "Montego Bay": { slug: "Montego-Bay", id: "432" },
  Aruba: { slug: "Aruba", id: "6284" },
  "St. Thomas": { slug: "St-Thomas", id: "965" },
  "St. Lucia": { slug: "St-Lucia", id: "38" },
  Barbados: { slug: "Barbados", id: "45" },
  "Grand Cayman": { slug: "Grand-Cayman", id: "31" },
  Antigua: { slug: "Antigua", id: "27" },
  Bahamas: { slug: "Bahamas", id: "419" },
  Jamaica: { slug: "Jamaica", id: "431" },
  "St. Maarten": { slug: "St-Maarten", id: "29" },
  "Turks and Caicos": { slug: "Turks-and-Caicos", id: "962" },
  Bermuda: { slug: "Bermuda", id: "30" },
  Curacao: { slug: "Curacao", id: "1300" },
  "St. Kitts": { slug: "St-Kitts", id: "26" },
  Grenada: { slug: "Grenada", id: "33" },
  Dominica: { slug: "Dominica", id: "34" },
  "St. Croix": { slug: "St-Croix", id: "966" },

  // Canada
  Toronto: { slug: "Toronto", id: "623" },
  Vancouver: { slug: "Vancouver", id: "616" },
  Montreal: { slug: "Montreal", id: "622" },
  "Quebec City": { slug: "Quebec-City", id: "624" },
  Victoria: { slug: "Victoria", id: "617" },
  Calgary: { slug: "Calgary", id: "619" },
  Ottawa: { slug: "Ottawa", id: "621" },
  "Niagara Falls Canada": { slug: "Niagara-Falls-Canada", id: "627" },
  Banff: { slug: "Banff", id: "620" },
  Whistler: { slug: "Whistler", id: "618" },
  Halifax: { slug: "Halifax", id: "625" },
  Edmonton: { slug: "Edmonton", id: "628" },
  Jasper: { slug: "Jasper", id: "629" },
  Winnipeg: { slug: "Winnipeg", id: "626" },
  "Lake Louise": { slug: "Lake-Louise", id: "630" },

  // UK
  London: { slug: "London", id: "737" },
  Edinburgh: { slug: "Edinburgh", id: "739" },
  Glasgow: { slug: "Glasgow", id: "740" },
  Manchester: { slug: "Manchester", id: "768" },
  Liverpool: { slug: "Liverpool", id: "770" },
  Bath: { slug: "Bath", id: "27175" },
  York: { slug: "York", id: "5431" },
  Oxford: { slug: "Oxford", id: "5537" },
  Cambridge: { slug: "Cambridge", id: "5602" },
  Belfast: { slug: "Belfast", id: "738" },
  Cardiff: { slug: "Cardiff", id: "5603" },
  Brighton: { slug: "Brighton", id: "5604" },
  Bristol: { slug: "Bristol", id: "5605" },
  Birmingham: { slug: "Birmingham-England", id: "5606" },
  Leeds: { slug: "Leeds", id: "5607" },
  Newcastle: { slug: "Newcastle", id: "5608" },
  Inverness: { slug: "Inverness", id: "5609" },
  Aberdeen: { slug: "Aberdeen", id: "5610" },
  "Stratford-upon-Avon": { slug: "Stratford-upon-Avon", id: "5611" },
  Canterbury: { slug: "Canterbury", id: "5612" },

  // France
  Paris: { slug: "Paris", id: "479" },
  Nice: { slug: "Nice", id: "478" },
  Lyon: { slug: "Lyon", id: "829" },
  Marseille: { slug: "Marseille", id: "485" },
  Bordeaux: { slug: "Bordeaux", id: "468" },
  Strasbourg: { slug: "Strasbourg", id: "490" },
  Toulouse: { slug: "Toulouse", id: "5053" },
  Cannes: { slug: "Cannes", id: "478" },
  Monaco: { slug: "Monaco", id: "478" },
  Avignon: { slug: "Avignon", id: "484" },
  "Aix-en-Provence": { slug: "Aix-en-Provence", id: "485" },
  "Saint-Tropez": { slug: "Saint-Tropez", id: "486" },
  Lille: { slug: "Lille", id: "5030" },
  Nantes: { slug: "Nantes", id: "5033" },
  Montpellier: { slug: "Montpellier", id: "5031" },
  Dijon: { slug: "Dijon", id: "5032" },
  Chamonix: { slug: "Chamonix", id: "5034" },

  // Asia
  Tokyo: { slug: "Tokyo", id: "334" },
  Kyoto: { slug: "Kyoto", id: "332" },
  Osaka: { slug: "Osaka", id: "333" },
  Bangkok: { slug: "Bangkok", id: "343" },
  Singapore: { slug: "Singapore", id: "18" },
  "Hong Kong": { slug: "Hong-Kong-SAR", id: "359" },
  Bali: { slug: "Bali", id: "98" },
  Seoul: { slug: "Seoul", id: "376" },
  Shanghai: { slug: "Shanghai", id: "321" },
  Beijing: { slug: "Beijing", id: "320" },
  Taipei: { slug: "Taipei", id: "5262" },
  Hanoi: { slug: "Hanoi", id: "351" },
  "Ho Chi Minh City": { slug: "Ho-Chi-Minh-City", id: "352" },
  "Kuala Lumpur": { slug: "Kuala-Lumpur", id: "338" },
  Manila: { slug: "Manila", id: "5263" },
  Phuket: { slug: "Phuket", id: "344" },
  "Chiang Mai": { slug: "Chiang-Mai", id: "345" },
  "Siem Reap": { slug: "Siem-Reap", id: "347" },
  Delhi: { slug: "New-Delhi", id: "356" },
  Mumbai: { slug: "Mumbai", id: "357" },

  // Central America
  "Panama City": { slug: "Panama-City", id: "950" },
  "San Jose": { slug: "San-Jose-Costa-Rica", id: "593" },
  "Antigua Guatemala": { slug: "Antigua", id: "4595" },
  "Belize City": { slug: "Belize-City", id: "4448" },
  Roatan: { slug: "Roatan", id: "4133" },
  Managua: { slug: "Managua", id: "4503" },
  "San Salvador": { slug: "San-Salvador", id: "4505" },
  Tegucigalpa: { slug: "Tegucigalpa", id: "4506" },
  Granada: { slug: "Granada-Nicaragua", id: "4508" },
  "Bocas del Toro": { slug: "Bocas-del-Toro", id: "4507" },

  // South America
  "Rio de Janeiro": { slug: "Rio-de-Janeiro", id: "712" },
  "Buenos Aires": { slug: "Buenos-Aires", id: "901" },
  Lima: { slug: "Lima", id: "928" },
  Cusco: { slug: "Cusco", id: "937" },
  Santiago: { slug: "Santiago", id: "800" },
  Bogota: { slug: "Bogota", id: "4563" },
  Medellin: { slug: "Medellin", id: "4564" },
  Quito: { slug: "Quito", id: "5023" },
  Cartagena: { slug: "Cartagena", id: "4565" },
  "Sao Paulo": { slug: "Sao-Paulo", id: "511" },
  "La Paz": { slug: "La-Paz", id: "5205" },
  Montevideo: { slug: "Montevideo", id: "5206" },
  "Machu Picchu": { slug: "Machu-Picchu", id: "937" },
  "Galapagos Islands": { slug: "Galapagos-Islands", id: "936" },
  "Easter Island": { slug: "Easter-Island", id: "801" },

  // Europe - Additional Countries
  Amsterdam: { slug: "Amsterdam", id: "525" },
  Berlin: { slug: "Berlin", id: "488" },
  Vienna: { slug: "Vienna", id: "499" },
  Prague: { slug: "Prague", id: "455" },
  Budapest: { slug: "Budapest", id: "499" },
  Athens: { slug: "Athens", id: "496" },
  Dublin: { slug: "Dublin", id: "503" },
  Lisbon: { slug: "Lisbon", id: "538" },
  Stockholm: { slug: "Stockholm", id: "533" },
  Copenhagen: { slug: "Copenhagen", id: "500" },
  Oslo: { slug: "Oslo", id: "902" },
  Helsinki: { slug: "Helsinki", id: "542" },
  Zurich: { slug: "Zurich", id: "577" },
  Geneva: { slug: "Geneva", id: "578" },
  Brussels: { slug: "Brussels", id: "458" },
  Krakow: { slug: "Krakow", id: "529" },
  Warsaw: { slug: "Warsaw", id: "530" },
  Istanbul: { slug: "Istanbul", id: "588" },

  // Middle East
  Dubai: { slug: "Dubai", id: "828" },
  "Abu Dhabi": { slug: "Abu-Dhabi", id: "827" },
  Doha: { slug: "Doha", id: "4157" },
  Jerusalem: { slug: "Jerusalem", id: "1022" },
  "Tel Aviv": { slug: "Tel-Aviv", id: "1023" },
  Cairo: { slug: "Cairo", id: "782" },
  Marrakech: { slug: "Marrakech", id: "825" },
  Casablanca: { slug: "Casablanca", id: "826" },
  Amman: { slug: "Amman", id: "786" },
  Muscat: { slug: "Muscat", id: "4156" },

  // Africa
  "Cape Town": { slug: "Cape-Town", id: "318" },
  Johannesburg: { slug: "Johannesburg", id: "317" },
  Nairobi: { slug: "Nairobi", id: "502" },
  Zanzibar: { slug: "Zanzibar", id: "8662" },
  "Victoria Falls": { slug: "Victoria-Falls", id: "319" },
  Marrakesh: { slug: "Marrakesh", id: "825" },
  Fez: { slug: "Fez", id: "824" },
  Luxor: { slug: "Luxor", id: "783" },

  // South Pacific
  Fiji: { slug: "Fiji", id: "41" },
  Tahiti: { slug: "Tahiti", id: "2" },
  "Bora Bora": { slug: "Bora-Bora", id: "2" },
  "Cook Islands": { slug: "Cook-Islands", id: "44" },
  Samoa: { slug: "Samoa", id: "43" },
  Tonga: { slug: "Tonga", id: "42" },

  // India
  Goa: { slug: "Goa", id: "355" },
  Jaipur: { slug: "Jaipur", id: "1075" },
  Agra: { slug: "Agra", id: "1074" },
  Varanasi: { slug: "Varanasi", id: "1076" },
  Kolkata: { slug: "Kolkata", id: "1077" },
  Chennai: { slug: "Chennai", id: "1078" },
  Bangalore: { slug: "Bangalore", id: "1079" },
  Hyderabad: { slug: "Hyderabad", id: "1080" },

  // Russia
  Moscow: { slug: "Moscow", id: "474" },
  "St. Petersburg": { slug: "St-Petersburg", id: "475" },

  // Scandinavia
  Reykjavik: { slug: "Reykjavik", id: "505" },
  Bergen: { slug: "Bergen", id: "903" },
  Tromso: { slug: "Tromso", id: "904" },
  Gothenburg: { slug: "Gothenburg", id: "534" },
  Malmo: { slug: "Malmo", id: "535" },
  Aarhus: { slug: "Aarhus", id: "501" },
  Tampere: { slug: "Tampere", id: "543" },
}

// Aliases for smaller towns/suburbs that redirect to major cities
export const viatorAliases: Record<string, string> = {
  // US Aliases
  // Newport is removed from aliases as it's now a direct destination
  "Santa Monica": "Los Angeles",

  "Cape Cod": "Boston",
  Brooklyn: "New York",
  Queens: "New York",
  Bronx: "New York",
  "Staten Island": "New York",
  Hollywood: "Los Angeles",
  "Beverly Hills": "Los Angeles",
  Malibu: "Los Angeles",
  Cambridge: "Boston",
  Somerville: "Boston",
  Quincy: "Boston",
  Brookline: "Boston",
  Waikiki: "Honolulu",
  "Pearl Harbor": "Honolulu",
  "South Beach": "Miami",
  "Key West": "Miami",
  "Napa Valley": "San Francisco",
  Sausalito: "San Francisco",
  Oakland: "San Francisco",
  Berkeley: "San Francisco",
  Georgetown: "Washington DC",
  Arlington: "Washington DC",
  Alexandria: "Washington DC",
  Epcot: "Orlando",
  "Disney World": "Orlando",
  "Universal Studios": "Orlando",

  SeaWorld: "Orlando",
  Disneyland: "Anaheim",
  "Universal Studios Hollywood": "Los Angeles",
  "French Quarter": "New Orleans",
  "Garden District": "New Orleans",
  "Fisherman's Wharf": "San Francisco",
  "Golden Gate Park": "San Francisco",
  Alcatraz: "San Francisco",
  "Times Square": "New York",
  "Central Park": "New York",
  "Wall Street": "New York",
  "Statue of Liberty": "New York",
  "Empire State Building": "New York",
  "South Beach": "Miami",
  "Little Havana": "Miami",
  Wynwood: "Miami",
  "Coconut Grove": "Miami",
  "The Strip": "Las Vegas",
  "Fremont Street": "Las Vegas",
  "Venice Beach": "Los Angeles",
  "Griffith Observatory": "Los Angeles",
  "Hollywood Walk of Fame": "Los Angeles",
  "Universal CityWalk": "Los Angeles",
  "Pike Place Market": "Seattle",
  "Space Needle": "Seattle",
  "Bourbon Street": "New Orleans",

  "Faneuil Hall": "Boston",
  "Fenway Park": "Boston",
  "Harvard University": "Boston",
  MIT: "Boston",
  Chinatown: "San Francisco",
  "North Beach": "San Francisco",
  "Mission District": "San Francisco",
  "Haight-Ashbury": "San Francisco",
  Presidio: "San Francisco",
  "Balboa Park": "San Diego",
  "Gaslamp Quarter": "San Diego",
  "Mission Bay": "San Diego",
  "Pacific Beach": "San Diego",
  "Old Town": "San Diego",
  Wrigleyville: "Chicago",
  "Magnificent Mile": "Chicago",
  "Navy Pier": "Chicago",
  "Millennium Park": "Chicago",
  "Lincoln Park": "Chicago",
  "Rittenhouse Square": "Philadelphia",
  "Old City": "Philadelphia",
  "South Street": "Philadelphia",
  "University City": "Philadelphia",
  Fishtown: "Philadelphia",

  // International Aliases
  Montmartre: "Paris",
  "Latin Quarter": "Paris",
  "Le Marais": "Paris",
  "Eiffel Tower": "Paris",
  Louvre: "Paris",
  Westminster: "London",
  "Covent Garden": "London",
  "Notting Hill": "London",
  Soho: "London",
  "Camden Town": "London",
  Shibuya: "Tokyo",
  Shinjuku: "Tokyo",
  Ginza: "Tokyo",
  Akihabara: "Tokyo",
  Roppongi: "Tokyo",
  "Playa Bavaro": "Punta Cana",
  "Isla Mujeres": "Cancun",
  "Puerto Morelos": "Cancun",
  "Riviera Maya": "Playa del Carmen",
  "San Jose del Cabo": "Cabo San Lucas",

  // European Aliases
  "Vatican City": "Rome",
  Trastevere: "Rome",
  "Spanish Steps": "Rome",
  Colosseum: "Rome",
  "Sagrada Familia": "Barcelona",
  "Gothic Quarter": "Barcelona",
  "La Rambla": "Barcelona",
  "Park Guell": "Barcelona",
  Kreuzberg: "Berlin",
  Mitte: "Berlin",
  Prenzlauer: "Berlin",
  Schöneberg: "Berlin",
  Jordaan: "Amsterdam",
  "De Pijp": "Amsterdam",
  "Red Light District": "Amsterdam",
  Vondelpark: "Amsterdam",

  // Asian Aliases
  Kowloon: "Hong Kong",
  "Victoria Peak": "Hong Kong",
  "Central District": "Hong Kong",
  "Lan Kwai Fong": "Hong Kong",
  Ubud: "Bali",
  Seminyak: "Bali",
  Kuta: "Bali",
  "Nusa Dua": "Bali",
  Pudong: "Shanghai",
  "The Bund": "Shanghai",
  "French Concession": "Shanghai",
  "Yu Garden": "Shanghai",

  // Australia & NZ Aliases
  "Bondi Beach": "Sydney",
  "Darling Harbour": "Sydney",
  "The Rocks": "Sydney",
  "Manly Beach": "Sydney",
  "St Kilda": "Melbourne",
  Fitzroy: "Melbourne",
  "South Bank": "Melbourne",
  "Chapel Street": "Melbourne",
  "Waiheke Island": "Auckland",
  "Viaduct Harbour": "Auckland",
  "Mission Bay": "Auckland",

  // Additional International Aliases
  "Burj Khalifa": "Dubai",
  "Palm Jumeirah": "Dubai",
  "Dubai Marina": "Dubai",
  "Old Dubai": "Dubai",
  Copacabana: "Rio de Janeiro",
  Ipanema: "Rio de Janeiro",
  "Christ the Redeemer": "Rio de Janeiro",
  "Sugar Loaf Mountain": "Rio de Janeiro",
  "Table Mountain": "Cape Town",
  "V&A Waterfront": "Cape Town",
  "Camps Bay": "Cape Town",
  "Robben Island": "Cape Town",
  "Cinque Terre": "La Spezia",
}
