// Extended Viator destination IDs with slugs and IDs
export const viatorDestinations: Record<string, { slug: string; id: string }> = {
  // USA
  Chicago: { slug: "Chicago", id: "673" },
  "New York": { slug: "New-York-City", id: "687" },
  Boston: { slug: "Boston", id: "678" },
  Miami: { slug: "Miami", id: "662" },
  "Los Angeles": { slug: "Los-Angeles", id: "645" },
  "San Francisco": { slug: "San-Francisco", id: "651" },
  Orlando: { slug: "Orlando", id: "663" },
  Seattle: { slug: "Seattle", id: "704" },
  Atlanta: { slug: "Atlanta", id: "784" },
  Denver: { slug: "Denver", id: "4837" },
  Phoenix: { slug: "Phoenix", id: "639" },
  Nashville: { slug: "Nashville", id: "799" },
  Dallas: { slug: "Dallas", id: "918" },
  Houston: { slug: "Houston", id: "5186" },
  Philadelphia: { slug: "Philadelphia", id: "906" },
  "San Diego": { slug: "San-Diego", id: "736" },
  "Las Vegas": { slug: "Las-Vegas", id: "684" },
  Honolulu: { slug: "Oahu", id: "590" },
  Portland: { slug: "Portland", id: "5064" },
  "Salt Lake City": { slug: "Salt-Lake-City", id: "5204" },
  "New Orleans": { slug: "New-Orleans", id: "675" },
  Austin: { slug: "Austin", id: "5021" },
  Tampa: { slug: "Tampa", id: "666" },
  Sacramento: { slug: "Sacramento", id: "5108" },
  Minneapolis: { slug: "Minneapolis-Saint-Paul", id: "5105" },
  "St Louis": { slug: "Saint-Louis", id: "5202" },
  "Kansas City": { slug: "Kansas-City", id: "5203" },
  Detroit: { slug: "Detroit", id: "5106" },
  Cleveland: { slug: "Cleveland", id: "5107" },
  Baltimore: { slug: "Baltimore", id: "5109" },
  Charlotte: { slug: "Charlotte", id: "5110" },
  Cincinnati: { slug: "Cincinnati", id: "5111" },
  Indianapolis: { slug: "Indianapolis", id: "5112" },
  Columbus: { slug: "Columbus", id: "5113" },
  Raleigh: { slug: "Raleigh", id: "5114" },
  Richmond: { slug: "Richmond", id: "5115" },
  Albuquerque: { slug: "Albuquerque", id: "5116" },
  Anchorage: { slug: "Anchorage", id: "5117" },
  Boise: { slug: "Boise", id: "5118" },
  "Des Moines": { slug: "Des-Moines", id: "5119" },
  Fargo: { slug: "Fargo", id: "5120" },
  Helena: { slug: "Helena", id: "5121" },
  Jackson: { slug: "Jackson", id: "5122" },
  "Little Rock": { slug: "Little-Rock", id: "5123" },
  Madison: { slug: "Madison", id: "5124" },
  Montgomery: { slug: "Montgomery", id: "5125" },
  Providence: { slug: "Providence", id: "5126" },
  Spokane: { slug: "Spokane", id: "5127" },
  Tulsa: { slug: "Tulsa", id: "5128" },
  Reno: { slug: "Reno", id: "5129" },
  Charleston: { slug: "Charleston", id: "5130" },
  Burlington: { slug: "Burlington", id: "5131" },
  Lexington: { slug: "Lexington", id: "5132" },
  Wichita: { slug: "Wichita", id: "5133" },
  "Baton Rouge": { slug: "Baton-Rouge", id: "5134" },
  "Green Bay": { slug: "Green-Bay", id: "5135" },
  "Fort Worth": { slug: "Fort-Worth", id: "5137" },
  Lubbock: { slug: "Lubbock", id: "5138" },
  Mesa: { slug: "Mesa", id: "5139" },
  Glendale: { slug: "Glendale", id: "5140" },
  "Chula Vista": { slug: "Chula-Vista", id: "5141" },
  Buffalo: { slug: "Buffalo", id: "5142" },
  Rochester: { slug: "Rochester", id: "5143" },
  Yonkers: { slug: "Yonkers", id: "5144" },
  Akron: { slug: "Akron", id: "5145" },
  Aurora: { slug: "Aurora", id: "5146" },
  Mobile: { slug: "Mobile", id: "5147" },
  Shreveport: { slug: "Shreveport", id: "5148" },
  Amarillo: { slug: "Amarillo", id: "5149" },
  Huntsville: { slug: "Huntsville", id: "5150" },
  Plano: { slug: "Plano", id: "5151" },
  Irvine: { slug: "Irvine", id: "5152" },
  Fremont: { slug: "Fremont", id: "5153" },
  Modesto: { slug: "Modesto", id: "5154" },

  // Mexico
  Cancun: { slug: "Cancun", id: "631" },
  "Mexico City": { slug: "Mexico-City", id: "628" },
  Tulum: { slug: "Tulum", id: "24324" },
  "Playa del Carmen": { slug: "Playa-del-Carmen", id: "5501" },
  Cozumel: { slug: "Cozumel", id: "632" },
  "Cabo San Lucas": { slug: "Los-Cabos", id: "656" },
  Guadalajara: { slug: "Guadalajara", id: "629" },
  "Puerto Vallarta": { slug: "Puerto-Vallarta", id: "630" },
  Merida: { slug: "Merida", id: "28240" },
  Oaxaca: { slug: "Oaxaca", id: "23477" },
  Monterrey: { slug: "Monterrey", id: "28817" },
  Puebla: { slug: "Puebla", id: "28792" },

  // Caribbean
  "Punta Cana": { slug: "Punta-Cana", id: "794" },
  Nassau: { slug: "Nassau", id: "420" },
  "Montego Bay": { slug: "Montego-Bay", id: "432" },
  "St Thomas": { slug: "St-Thomas", id: "965" },
  Aruba: { slug: "Aruba", id: "6284" },
  "St Lucia": { slug: "St-Lucia", id: "38" },
  Barbados: { slug: "Barbados", id: "45" },
  "Grand Cayman": { slug: "Grand-Cayman", id: "31" },
  "San Juan": { slug: "San-Juan", id: "36" },
  Antigua: { slug: "Antigua", id: "27" },

  // UK
  London: { slug: "London", id: "737" },
  Edinburgh: { slug: "Edinburgh", id: "739" },
  Glasgow: { slug: "Glasgow", id: "740" },
  Manchester: { slug: "Manchester", id: "768" },
  Liverpool: { slug: "Liverpool", id: "770" },
  Bath: { slug: "Bath", id: "27175" },
  York: { slug: "York", id: "5431" },
  Oxford: { slug: "Oxford", id: "5537" },
  Cambridge: { slug: "Cambridge", id: "5602" },
  Belfast: { slug: "Belfast", id: "738" },

  // France
  Paris: { slug: "Paris", id: "479" },
  Nice: { slug: "Nice", id: "478" },
  Lyon: { slug: "Lyon", id: "829" },
  Marseille: { slug: "Marseille", id: "485" },
  Bordeaux: { slug: "Bordeaux", id: "468" },
  Strasbourg: { slug: "Strasbourg", id: "490" },
  Toulouse: { slug: "Toulouse", id: "5053" },
  Nantes: { slug: "Nantes", id: "5033" },
  Montpellier: { slug: "Montpellier", id: "5031" },
  Lille: { slug: "Lille", id: "5030" },

  // Asia
  Tokyo: { slug: "Tokyo", id: "334" },
  Kyoto: { slug: "Kyoto", id: "332" },
  Osaka: { slug: "Osaka", id: "333" },
  Bangkok: { slug: "Bangkok", id: "343" },
  Singapore: { slug: "Singapore", id: "18" },
  Bali: { slug: "Bali", id: "98" },
  Hanoi: { slug: "Hanoi", id: "351" },
  "Ho Chi Minh": { slug: "Ho-Chi-Minh-City", id: "352" },
  Seoul: { slug: "Seoul", id: "376" },
  Taipei: { slug: "Taipei", id: "5262" },

  // Central America
  "Panama City": { slug: "Panama-City", id: "950" },
  "San Jose": { slug: "San-Jose", id: "593" },
  "Antigua Guatemala": { slug: "Antigua", id: "4595" },
  Managua: { slug: "Managua", id: "4503" },
  "San Salvador": { slug: "San-Salvador", id: "4505" },
  Tegucigalpa: { slug: "Tegucigalpa", id: "4506" },
  "Belize City": { slug: "Belize-City", id: "4448" },
  Roatan: { slug: "Roatan", id: "4133" },
  "Bocas Del Toro": { slug: "Bocas-del-Toro", id: "4507" },
  Granada: { slug: "Granada", id: "4508" },

  // South America
  "Buenos Aires": { slug: "Buenos-Aires", id: "901" },
  "Rio de Janeiro": { slug: "Rio-de-Janeiro", id: "712" },
  "Sao Paulo": { slug: "Sao-Paulo", id: "511" },
  Lima: { slug: "Lima", id: "928" },
  Cusco: { slug: "Cusco", id: "937" },
  Santiago: { slug: "Santiago", id: "800" },
  Bogota: { slug: "Bogota", id: "4563" },
  Medellin: { slug: "Medellin", id: "4564" },
  Quito: { slug: "Quito", id: "5023" },
  "La Paz": { slug: "La-Paz", id: "5205" },
}
